language: java
jdk:
- openjdk11
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
before_install:
- openssl.exe aes-256-cbc -K bd8d9fc5d6cfeebebe27d4b2222686bd54fcd026a637604a91e1130827006a1d -iv 2780a149fb4622fcb90461f0d857873f -in aws.tar -out aws.tar.enc -d
- chmod +x gradlew
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - dnajwm1995@gmail.com
