language: java
jdk:
- openjdk11
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
before_install:
- openssl enc -aes-256-cbc -in aws.tar -out aws.tar.enc -K 0bfbaa980753654535ae61e2dfb220e0939f6b5edec92d219efa0e62c85920be  -iv 42f3a2226eac279a5952376e6c843063
- chmod +x gradlew
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - dnajwm1995@gmail.com
