language: java
jdk:
- openjdk11
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
before_install:
- openssl enc aes-256-cbc -in application-aws.properties.enc -out application-aws.properties -d -K $encrypted_a6c7bc5d9194_key -iv $encrypted_a6c7bc5d9194_iv
#  -in application-aws.properties.enc -out application-aws.properties -d
- chmod +x gradlew
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - dnajwm1995@gmail.com
